# ===== symbol_config.py (새 파일) =====
"""
심볼 설정을 중앙 관리하는 파일
"""

# 시총 100위 종목 (바이낸스 USDT 페어)
TOP_100_SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT",
    "SHIBUSDT", "AVAXUSDT", "TRXUSDT", "DOTUSDT", "BCHUSDT", "NEARUSDT", "MATICUSDT",
    "ICPUSDT", "UNIUSDT", "LTCUSDT", "ETCUSDT", "APTUSDT", "STXUSDT", "CROUSDT", "OKBUSDT",
    "ATOMUSDT", "FILUSDT", "IMXUSDT", "VETUSDT", "MNTUSDT", "ARBUSDT", "HBARUSDT", "OPUSDT",
    "MKRUSDT", "AAVEUSDT", "GRTUSDT", "SEIUSDT", "SUIUSDT", "THETAUSDT", "RUNEUSDT", "FTMUSDT",
    "ALGOUSDT", "FLOWUSDT", "SANDUSDT", "XLMUSDT", "AXSUSDT", "MANAUSDT", "CHZUSDT", "EGLDUSDT",
    "KCSUSDT", "XTZUSDT", "EOSUSDT", "CAKEUSDT", "QNTUSDT", "ASTRUSDT", "KLAYUSDT", "NEOUSDT",
    "IOTAUSDT", "BSVUSDT", "XMRUSDT", "COMPUSDT", "ZECUSDT", "DASHUSDT", "WAVESUSDT", "QTUMUSDT",
    "BATUSDT", "DYDXUSDT", "CRVUSDT", "ENJUSDT", "1INCHUSDT", "ZILUSDT", "SUSHIUSDT", "YFIUSDT",
    "RENUSDT", "BNTUSDT", "SNXUSDT", "UMAUSDT", "STORJUSDT", "BALUSDT", "NMRUSDT", "LRCUSDT",
    "KNCUSDT", "BANDUSDT", "RSRUSDT", "RLCUSDT", "REPUSDT", "ZRXUSDT", "OXTUSDT", "MLNUSDT",
    "ALPHAUSDT", "MASKUSDT", "TRUUSDT", "RADUSDT", "BONDUSDT", "POOLUSDT", "FOXUSDT", "REQUSDT",
    "POLYUSDT", "REEFUSDT", "POLSUSDT", "OGNUSDT", "NKNUSDT", "LPTUSDT", "ANKRUSDT", "CVCUSDT",
    "GNOUSDT", "RARIUSDT", "FXSUSDT", "CVXUSDT", "OCEANUSDT", "FETUSDT", "AGIXUSDT", "RNDRUSDT",
    "INJUSDT", "CFGUSDT", "COTIUSDT", "ERGUSDT", "CKBUSDT"
]

# AI 예측 대상 30개 종목
AI_PREDICTION_SYMBOLS = [
    "NMRUSDT", "OPUSDT", "ENJUSDT", "STXUSDT", "RLCUSDT", "COTIUSDT", "RUNEUSDT", "SUSHIUSDT",
    "CRVUSDT", "AVAXUSDT", "APTUSDT", "FILUSDT", "GNOUSDT", "FETUSDT", "ADAUSDT", "ANKRUSDT",
    "FLOWUSDT", "SNXUSDT", "YFIUSDT", "MANAUSDT", "RSRUSDT", "IMXUSDT", "FXSUSDT", "THETAUSDT",
    "SHIBUSDT", "XYOUSDT", "DYDXUSDT", "ICPUSDT", "ALGOUSDT", "DASHUSDT"
]

# 기본 거래 가능 종목 (기존 10개 + 확장)
DEFAULT_TRADING_SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT", "LINKUSDT",
    "LTCUSDT", "BCHUSDT", "XLMUSDT", "EOSUSDT", "TRXUSDT",
    # 추가 주요 종목
    "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "AVAXUSDT",
    "MATICUSDT", "ATOMUSDT", "NEARUSDT", "SANDUSDT", "MANAUSDT"
]

def get_symbol_list(category='default'):
    """카테고리별 심볼 목록 반환"""
    if category == 'top100':
        return TOP_100_SYMBOLS
    elif category == 'ai_prediction':
        return AI_PREDICTION_SYMBOLS
    elif category == 'default':
        return DEFAULT_TRADING_SYMBOLS
    else:
        return DEFAULT_TRADING_SYMBOLS

